
#define KC_UNDO LCTL(KC_Z)
#define KC_CUT LCTL(KC_X)
#define KC_COPY LCTL(KC_C)
#define KC_PASTE LCTL(KC_V)
#define KC_REDO LCTL(KC_Y)
#define KC_WIN_CHANGE LALT(LCTL(KC_TAB))
#define KC_LAN_CHANGE LALT(LSFT(KC_NO))
#define XXX KC_TRANSPARENT
#define VOL_UP KC_AUDIO_VOL_UP
#define VOL_DOWN KC_AUDIO_VOL_DOWN
#define KC_L_ANG_BRC KC_LEFT_ANGLE_BRACKET
#define KC_R_ANG_BRC KC_RIGHT_ANGLE_BRACKET
#define LCTL_MT_PLUS LCTL_T(KC_NO)

enum custom_keycodes {
    RGB_SLD = EZ_SAFE_RANGE,
    last,
};
